
name: CI - Main
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t example_python_package_image .
        docker run --rm example_python_package_image /bin/bash -c "bash run_tests.sh"